polenovo/urls.py
from django.urls import path, include

from polenovo import views

app_name='polenovo'

urlpatterns = [
    path('', views.index, name='index'),
    path('cl', views.cl_view, name='cl'),
    path('test', views.test_view, name='test'),
    path('chv',views.HomeView.as_view(), name='home'),
    path('plantv',views.CheckListView.as_view(), name='clv'),

]

users/urls.py
from django.urls import path

from users import views
app_name='users'
urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),
]

vitrich/urls.py
from django.contrib import admin
from django.urls import path, include
from polenovo import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polenovo.urls')),
    path('users/', include('users.urls', namespace="users")),

]

polenovo/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Plants(models.Model):
    title = models.CharField(max_length=255)
    titleL = models.CharField(max_length=255)
    family = models.CharField(max_length=255)
    maxPoints=models.IntegerField(default=0)
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        pass
        # return reverse('books:author_detail', kwargs={'pk': self.pk})



class Team(models.Model):
    title = models.CharField(max_length=255)
    school=models.CharField(max_length=255)
    points=models.IntegerField(default=0)
    expert=models.ForeignKey('Expert', on_delete=models.PROTECT,default=None)
    plants = models.ManyToManyField(Plants, through="CheckList",related_name='team')

    # Categories
    CATEGORIES = (
        ('РВ', 'Разновозрастные'),
        ('В', 'Взрослые'),
        ('Э', 'Эксперты'),
        ('М', 'Младшие школьники'),
    )

    category = models.CharField(max_length=300, choices=CATEGORIES, default=None)

    def __str__(self):
        return self.title

class Expert(models.Model):
    name = models.CharField(max_length=255)
    phone =models.CharField(max_length=255,default=None)

    def __str__(self):
        return self.name

RES = [
    (0, 'Не определен'),
    (1, 'До семейства'),
    (2, 'До вида'),
]

class CheckList(models.Model): #https://metanit.com/python/django/5.7.php
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    plant = models.ForeignKey(Plants, on_delete=models.CASCADE)
    N=models.CharField(max_length=255,default=None)
    date = models.DateField(auto_now_add=True)
    vid=models.BooleanField(default=False)
    fam=models.BooleanField(default=False)



...

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    phone = models.CharField(max_length=255)

polenovo/forms.py
from django import forms
from django.forms import IntegerField, BooleanField
from .models import CheckList, Plants


class CLForm(forms.Form):
    # create new form object from database question object
    def __init__(
            self,
            team,
            plantC,
            plantT,
            fam,
            vid,
    ):
        super().__init__()
        self.fam = fam
        self.vid = vid
        self.plantC = plantC
        self.plantT = plantT
        self.team = team







class Test_Form(forms.Form):
    # class Meta:
    #     model = CheckList
    #     fields = ['vid','fam']
    #     labels = {
    #         'vid': 'Вид:',
    #         'fam': 'Семейство:'
    #     }
    fam=forms.BooleanField(initial=False,required=False)
    vid=forms.BooleanField(initial=False,required=False)

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username',  'first_name', 'last_name', 'password1', 'password2']
        labels = {

            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email
class LoginUserForm(forms.Form):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

polenovo/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.forms import formset_factory, forms, BooleanField, modelformset_factory
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.views.generic import TemplateView, ListView

from polenovo.forms import CLForm, Test_Form
from polenovo.models import Plants, CheckList, Team


def index(request):
    return render(request, 'polenovo/index.html')


def cl_view(request):
    Formset = modelformset_factory(CheckList, fields=('N', 'fam', 'vid'))

    if request.method == 'POST':
        form = Formset(request.POST)
        form.save()
        return redirect("index")
    else:
        team = Team.objects.first()
        rawPl = Plants.objects.all()
        for pl in rawPl:
            cl = CheckList(
                team=team,
                plant=pl,
                N=pl.title
            )
            cl.save()

    form = Formset()
    context = {
        "form": form
    }

    return render(request, "polenovo/checklist.html", context)


def test_view(request):
    team = Team.objects.first()

    Pl = Plants.objects.first(

    )
    form = Test_Form()

    if request.method == 'POST':
        form = Test_Form(request.POST)
        if form.is_valid():
            cl = CheckList(
                team=team,
                plant=Pl,
                fam=form.cleaned_data['fam'],
                vid=form.cleaned_data['vid']
            )
            cl.save()
    else:
        form = form
    context = {
        "form": form
    }

    return render(request, "polenovo/test.html", context)


class HomeView(TemplateView):
    template_name = 'polenovo\home.html'


class CheckListView(ListView):
    model = CheckList
    template_name = 'CheckList_list.html'

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from users.forms import RegisterUserForm, LoginUserForm


def login_user(request):
    if request.method == 'POST':
        form = LoginUserForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user and user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
    else:
        form = LoginUserForm()
    return render(request, 'users/login.html', {'form': form})

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))

def register(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)  # создание объекта без сохранения в БД
            user.set_password(form.cleaned_data['password'])
            user.save()
            return render(request, 'users/register_done.html')
    else:
        form = RegisterUserForm()
    return render(request, 'users/register.html', {'form': form})

templates/polenovo/CheckList_list.html
{% extends 'polenovo/basev.html' %}

{% block title %}Plants{% endblock %}

{% block content %}

<h1 class="h3">Plants</h1>

 {% if checklist_list %}

    <ul class="list-group">
      {% for plant in checklist_list %}
        <li class="list-group-item">
          <a class="text-reset" href="{{ plant.get_absolute_url }}">{{ plant.N }}</a>
        </li>
      {% endfor %}
    </ul>

  {% else %}

    <p>There are no author to display.</p>

  {% endif %}

    <p class="pt-2">
      <a href="{% url 'polenovo:home' %}" role="button" class="btn btn-secondary w-100">Cancel</a>
    </p>

{% endblock content %}

templates/polenovo/Plants_list.html
{% extends 'polenovo/basev.html' %}

{% block title %}Plants{% endblock %}

{% block content %}

<h1 class="h3">Plants</h1>

 {% if plants_list %}

    <ul class="list-group">
      {% for plant in plants_list %}
        <li class="list-group-item">
          <a class="text-reset" href="{{ plant.get_absolute_url }}">{{ plant.title }}</a>
        </li>
      {% endfor %}
    </ul>

  {% else %}

    <p>There are no author to display.</p>

  {% endif %}

    <p class="pt-2">
      <a href="{% url 'polenovo:home' %}" role="button" class="btn btn-secondary w-100">Cancel</a>
    </p>

{% endblock content %}

templates/polenovo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <head>
        <title>{% block title %}{% endblock %}</title>
        {% load bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>
</head>
<body>
<div id="sidebar">
    {% block sidebar %}
        <ul class="nav bg-info">
            <li class="nav-item">
                <a class="nav-link link-light" href="/">В начало</a>
            </li>
            <li class="nav-item">
                <a class="nav-link link-light" href="{% url 'polenovo:index' %}">Эксперты</a>
            </li>
            <li class="nav-item">
                <a class="nav-link link-light" href="/admin">Администрирование</a>

            </li>
            <li class="nav-item">
                <a class="nav-link link-light" href="/cl">Чеклист</a>
            </li>
        <li class="nav-item">
                <a class="nav-link link-light" href="{% url 'polenovo:home' %}">View</a>
            </li>
            {% if user.is_authenticated %}
                </li>
                <li class="nav-item">
                    <a class="nav-link link-light" href="{% url 'users:logout' %}">Выход</a>
                </li>
            {% else %}
                </li>
                <li class="nav-item">
                    <a class="nav-link link-light" href="{% url 'users:login' %}">Вход</a>

                </li>
                <li class=nav-item><a class="nav-link link-light" href="{% url 'users:register' %}">Регистрация</a></li>
            {% endif %}


        </ul>
    {% endblock %}
</div>
<div id="content">
    {% block content %}{% endblock %}
</div>
</body>
</html>

templates/polenovo/basev.html
<!doctype html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <title>{% block title %}Homepage{% endblock %}</title>
  </head>
  <body>
    <main>
      <div class="container-fluid">
        <div class="d-flex align-items-center py-5">
          <div class="col-12 col-md-6 col-lg-4 mx-auto">
            {% block content %}
            {% endblock content %}
          </div>
        </div>
      </div>
    </main>
  </body>
</html>

templates/polenovo/change_list.html
{% extends 'admin/change_list.html' %}
{% load static %}

{% block object-tools-items %}
<li>
    <a href="csv-upload/" class="addlink">
      Импорт
    </a>
</li>
{{ block.super }}
{% endblock %}

templates/polenovo/checklist.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>

<div class="container">
  <ul class="nav bg-info">
    <li class="nav-item">
      <a class="nav-link link-light" href="/">В начало</a>
    </li>
    <li class="nav-item">
      <a class="nav-link link-light" href="{% url 'polenovo:index'  %}">Эксперты</a>
    </li><li class="nav-item">
      <a class="nav-link link-light" href="/admin">Администрирование</a>

      </li><li class="nav-item">
      <a class="nav-link link-light" href="/cl">Чеклист</a>
    </li>
  </ul>

  {% block content %}
  {% endblock %}
</div>

<hr>
    <form   method="post">
        {% csrf_token %}
        <button type="submit">Submit</button>
        <div>
            {{ form.as_div}}

        </div>
    <button type="submit">Submit</button>
    </form>
</body>
</html>

templates/polenovo/csv_import_page.html
{% extends 'admin/base.html' %}

{% block content %}
    <div>
        <form action="" method="POST" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}
            <button type="submit">Загрузка CSV</button>
        </form>
    </div>
{% endblock %}

templates/polenovo/home.html
{% extends 'polenovo/basev.html' %}

{% block title %}Homepage{% endblock %}

{% block content %}

    <h3>BookStore Collections</h3>
    <a href="{% url 'polenovo:clv' %}" role="button" class="btn btn-primary w-100 mb-2">Все растения</a>
    <a href="{% url 'polenovo:home' %}" role="button" class="btn btn-secondary w-100">Add an Author</a>

{% endblock content %}

templates/polenovo/index.html
{% extends 'polenovo/base.html' %}

{% block content %}
  Hi
{% endblock %}

templates/polenovo/test.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>

<div class="container">
  <ul class="nav bg-info">
    <li class="nav-item">
      <a class="nav-link link-light" href="/">В начало</a>
    </li>
    <li class="nav-item">
      <a class="nav-link link-light" href="{% url 'index'  %}">Эксперты</a>
    </li><li class="nav-item">
      <a class="nav-link link-light" href="/admin">Администрирование</a>

      </li><li class="nav-item">
      <a class="nav-link link-light" href="/cl">Чеклист</a>
    </li>
  </ul>

  {% block content %}
  {% endblock %}
</div>

<hr>
    <form   method="post">
        {% csrf_token %}
        <button type="submit">Submit</button>
        <div>
            {{ form.as_p}}

        </div>

    </form>
</body>
</html>